id: P8FFF77EA
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA20108
  instance_id: http://purl.bdrc.io/resource/IE20108
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྟགས་འཇུག་དཀའ་གནད་གསལ་བའི་མེ་ལོང་།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P4942
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    1eac58beea9748f792804575f239b723:
      title: པོད ༡་རྟགས་འཇུག་དཀའ་གནད་གསལ་བའི་མེ་ལོང
      volume_number: 1
      base_file: UT20108_4738_0000.txt
      reference: http://purl.bdrc.io/resource/VL56111C58AFE09552
      image_group: '4738'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW20108
  - http://purl.bdrc.io/resource/W20108
  ocr_software: Namsel
created_at: '2021-12-22T11:04:53.647195'
last_modified_at: '2021-12-22T11:04:53.647202'
statistics:
  total_words: 15381
  total_non_words: 2714
quality:
  non_words_ratio: 0.18
